# Generated by Django 6.0.5 on 2026-05-16 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('blocked_attempt', 'Blocked Attempt'), ('app_opened', 'App Opened'), ('screen_time_updated', 'Screen Time Updated'), ('vpn_started', 'VPN Started'), ('vpn_stopped', 'VPN Stopped'), ('rule_triggered', 'Rule Triggered'), ('focus_session_started', 'Focus Session Started'), ('relapse_detected', 'Relapse Detected')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='device_control.device')),
            ],
        ),
    ]
