# Generated by Django 6.0.5 on 2026-05-16 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('app', 'App'), ('website', 'Website'), ('category', 'Category')], max_length=20)),
                ('target', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=1)),
                ('schedule', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='device_control.device')),
            ],
        ),
    ]
