# Generated by Django 6.0.5 on 2026-05-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_control', '0001_initial'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockingrule',
            options={'ordering': ['-priority']},
        ),
        migrations.AddConstraint(
            model_name='blockingrule',
            constraint=models.UniqueConstraint(fields=('device', 'rule_type', 'target'), name='unique_rule'),
        ),
    ]
